1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [30]:
import numpy as np

a = np.arange(1, 11, 1)
print(a)



[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [11]:
b = np.zeros((3,3),dtype=int)
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [20]:
import random
import numpy as np

m = np.ones((5, 5), dtype=int)

for i in range(1,6):
  for j in range(1,6):
    m [i-1][j-1] = random.randint(1,10)

print(m)

[[ 9  6  5  5  8]
 [ 9  6 10  6 10]
 [ 7  3  8  5  3]
 [ 5  8  5  2  9]
 [ 5  5  2  7  8]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [70]:
import random
import numpy as np

b = np.random.random((4, 4))

print(b)

[[0.75426407 0.2856175  0.28964191 0.62579985]
 [0.47239273 0.34046085 0.94746776 0.45792179]
 [0.91995727 0.8048474  0.69805331 0.24641015]
 [0.95311077 0.24384824 0.12433455 0.5106484 ]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [45]:
rng = np.random.default_rng()
a = rng.integers(1,11,5)
print("a:\n",a)
b = rng.integers(1,11,5)
print("b:\n",b)

a_plus_b = a+b
print("a_plus_b:\n",a_plus_b)
a_minus_b = a - b
print("a_minus_b:\n",a_minus_b)
a_multiple_b = a * b
print("a_multiple_b:\n",a_multiple_b)


a:
 [1 8 7 9 3]
b:
 [3 7 6 6 5]
a_plus_b:
 [ 4 15 13 15  8]
a_minus_b:
 [-2  1  1  3 -2]
a_multiple_b:
 [ 3 56 42 54 15]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [66]:
c = np.random.random(7)
print("c: \n",c)
d = np.random.random(7)
print("d: \n",d)
c_mult_d = c*d
print("c_mult_d: \n",c_mult_d)

c: 
 [0.04127394 0.17207948 0.10374506 0.82566443 0.76186167 0.55245984
 0.0242994 ]
d: 
 [0.70809154 0.15339156 0.35946883 0.58253576 0.86202761 0.42390649
 0.00767204]
c_mult_d: 
 [2.92257254e-02 2.63955396e-02 3.72931172e-02 4.80979055e-01
 6.56745789e-01 2.34191308e-01 1.86425888e-04]


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [59]:
rng = np.random.default_rng()
e = rng.integers(1,11,(2,2))
print("e:\n",e)
f = rng.integers(1,11,(2,3))
print("f:\n",f)

e_dot_f = np.dot(e,f)
print("e_dot_f:\n",e_dot_f)

e:
 [[3 5]
 [1 6]]
f:
 [[ 2  2  5]
 [ 3  1 10]]
e_dot_f:
 [[21 11 65]
 [20  8 65]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [62]:
rng = np.random.default_rng()
g = rng.integers(1,11,(3,3))
print("g:\n",d)

g_t = g.T
print("g_t:\n",g_t)

g:
 [[ 4  8  3]
 [ 3  9 10]
 [ 3  5  2]]
g_t:
 [[ 6  5  7]
 [10  2  2]
 [ 3  9  7]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [64]:
h = np.random.random((4,4))
print("h: \n",h)
h_T = h.T
print("h_T: \n",h_T)

h: 
 [[0.54221887 0.86298212 0.59712724 0.10305713]
 [0.4579516  0.92252393 0.77629868 0.29009196]
 [0.48629641 0.43789003 0.21938662 0.00426368]
 [0.87269338 0.67648844 0.93316303 0.04023816]]
h_T: 
 [[0.54221887 0.4579516  0.48629641 0.87269338]
 [0.86298212 0.92252393 0.43789003 0.67648844]
 [0.59712724 0.77629868 0.21938662 0.93316303]
 [0.10305713 0.29009196 0.00426368 0.04023816]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [65]:
rng = np.random.default_rng()
e = rng.integers(1,11,(3,4))
print("e:\n",e)
f = rng.integers(1,11,(4))
print("f:\n",f)

e_dot_f = np.dot(e,f)
print("e_dot_f:\n",e_dot_f)

e:
 [[ 9 10  2  6]
 [10  7  4  8]
 [10  5  9  9]]
f:
 [1 7 5 7]
e_dot_f:
 [131 135 153]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [69]:
j = np.random.random((2,3))
print("j: \n",j)
k = np.random.random((3))
print("k: \n",k)
j_dot_k = np.dot(j,k)
print("j_dot_k: \n",j_dot_k)

j: 
 [[0.76436189 0.50264357 0.98833995]
 [0.88701412 0.92194913 0.78687198]]
k: 
 [0.90927271 0.74182621 0.55985105]
j_dot_k: 
 [1.62121074 1.93099486]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [71]:
rng = np.random.default_rng()
e = rng.integers(1,11,(2,2))
print("e:\n",e)
f = rng.integers(1,11,(2,2))
print("f:\n",f)

e_mult_f = e * f
print("e_mult_f:\n",e_mult_f)

e:
 [[ 8  2]
 [10  3]]
f:
 [[5 3]
 [6 5]]
e_mult_f:
 [[40  6]
 [60 15]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [72]:
rng = np.random.default_rng()
e = rng.integers(1,11,(2,2))
print("e:\n",e)
f = rng.integers(1,11,(2,2))
print("f:\n",f)

e_dot_f = np.dot(e,f)
print("e_dot_f:\n",e_dot_f)

e:
 [[7 4]
 [6 4]]
f:
 [[ 5  3]
 [10  5]]
e_dot_f:
 [[75 41]
 [70 38]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [74]:
rng = np.random.default_rng()
n = rng.integers(1,101,(5,5))
print("n:\n",n)
print("n.sum()=",n.sum())

n:
 [[ 25  41  41  44  96]
 [ 83 100  61   8  64]
 [ 22  18  54  88  69]
 [ 64   6 100  86  33]
 [ 60   1  89  21  79]]
n.sum()= 1353


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [75]:
rng = np.random.default_rng()
k = rng.integers(1,11,(4,4))
print("k:\n",k)
m = rng.integers(1,11,(4,4))
print("m:\n",m)
k_minus_m = k - m
print("k_minus_m:\n",k_minus_m)

k:
 [[ 2  9  6 10]
 [ 2  1 10 10]
 [ 6  7  1 10]
 [ 6 10  3  1]]
m:
 [[ 2  1 10  5]
 [ 4  4  6  1]
 [ 4  4  2  9]
 [ 8  3  2  5]]
k_minus_m:
 [[ 0  8 -4  5]
 [-2 -3  4  9]
 [ 2  3 -1  1]
 [-2  7  1 -4]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [76]:
j = np.random.random((3,3))
print("j: \n",j)

sum_of_rows = np.sum(j,axis=1)
column_vector = sum_of_rows[:, np.newaxis]
print("column_vector: \n",column_vector)

j: 
 [[0.91441932 0.48791162 0.85991337]
 [0.64640177 0.00166714 0.63551177]
 [0.68311051 0.66666399 0.20075045]]
column_vector: 
 [[2.26224431]
 [1.28358068]
 [1.55052494]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створіnь матрицю з квадратами цих чисел.

In [80]:
rng = np.random.default_rng()
n = rng.integers(1,101,(3,4))
print("n:\n",n)
k = np.copy(n)
print("k:\n",k)
n_pow_2 = n * k
print("n_pow_2:\n",n_pow_2)

n:
 [[74 17 50  8]
 [12 95 43 77]
 [66 99  3 26]]
k:
 [[74 17 50  8]
 [12 95 43 77]
 [66 99  3 26]]
n_pow_2:
 [[5476  289 2500   64]
 [ 144 9025 1849 5929]
 [4356 9801    9  676]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [85]:
rng = np.random.default_rng()
j = rng.integers(1,51,(4))
print("j: \n",j)

sqrt_of_rows = np.sqrt(j)
column_vector = sqrt_of_rows[:, np.newaxis]
print("column_vector: \n",column_vector)

j: 
 [12 17 27 27]
column_vector: 
 [[3.46410162]
 [4.12310563]
 [5.19615242]
 [5.19615242]]
